import { useEffect, useState } from 'react'
import PageLayout from '../../components/dashboard/PageLayout.jsx'
import Loading from '../../components/common/Loading.jsx'
import EmptyState from '../../components/common/EmptyState.jsx'
import StatusBadge from '../../components/common/StatusBadge.jsx'
import Button from '../../components/common/Button.jsx'
import { donationsAPI } from '../../services/api.js'

export default function MyDonations(){const [donations,setDonations]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=()=>donationsAPI.mine().then(({data})=>setDonations(data.donations||[])).catch(()=>setError('Could not load your donations.')).finally(()=>setLoading(false));useEffect(()=>{load()},[]);const update=async(id,status)=>{try{await donationsAPI.update(id,{status});await load()}catch(err){setError(err.response?.data?.message||'Could not update this offer.')}};return <PageLayout eyebrow="YOUR IMPACT" title="My donations" description="Track each offer from first response through safe handover.">{error&&<div className="message error">{error}</div>}{loading?<Loading/>:donations.length?<div className="record-list">{donations.map(donation=><article key={donation._id}><div><div className="record-title"><h3>{donation.need?.title||donation.itemName}</h3><StatusBadge status={donation.status}/></div><p>{donation.description||`${donation.quantity} item${donation.quantity===1?'':'s'} offered in ${donation.condition} condition.`}</p><small>{donation.location} · {donation.category} · {new Date(donation.createdAt).toLocaleDateString()}</small>{donation.handoverNotes&&<div className="review-note"><strong>Handover:</strong> {donation.handoverNotes}</div>}</div><div className="record-actions">{donation.status==='Matched'&&<Button onClick={()=>update(donation._id,'Coordinating')}>Start coordination</Button>}{['Offered','Available'].includes(donation.status)&&<Button className="danger" onClick={()=>update(donation._id,'Cancelled')}>Withdraw</Button>}{donation.status==='Coordinating'&&<Button onClick={()=>update(donation._id,'Completed')}>Mark completed</Button>}</div></article>)}</div>:<EmptyState title="No offers yet" message="Browse available needs to find someone you can help."/>}</PageLayout>}
