import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import PageLayout from '../../components/dashboard/PageLayout.jsx'
import StatusBadge from '../../components/common/StatusBadge.jsx'
import Loading from '../../components/common/Loading.jsx'
import DonationForm from '../../components/donations/DonationForm.jsx'
import { donationsAPI, needsAPI } from '../../services/api.js'
import { useAuth } from '../../context/AuthContext.jsx'

export default function NeedDetails(){const {id}=useParams();const {user}=useAuth();const [need,setNeed]=useState(null);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>{needsAPI.get(id).then(({data})=>setNeed(data.need)).catch(err=>setError(err.response?.data?.message||'Could not load this need.'))},[id]);const submit=async form=>{setSaving(true);setError('');try{await donationsAPI.create(form);setSuccess('Your offer was sent. You can track it in My donations.')}catch(err){setError(err.response?.data?.message||'Could not send your offer.')}finally{setSaving(false)}};return <PageLayout eyebrow="VERIFIED NEED" title={need?.title||'Need details'} actions={<Link className="button secondary" to="/available-needs">Back to needs</Link>}>{error&&<div className="message error">{error}</div>}{!need&&!error?<Loading/>:need&&<div className="detail-grid"><article className="panel"><div className="panel-heading"><h2>{need.title}</h2><StatusBadge status={need.verificationStatus}/></div><p>{need.description}</p><dl><div><dt>Category</dt><dd>{need.category}</dd></div><div><dt>Approximate location</dt><dd>{need.location}</dd></div><div><dt>Urgency</dt><dd>{need.urgency}</dd></div><div><dt>Progress</dt><dd>{need.quantityFulfilled} of {need.quantityNeeded} fulfilled</dd></div></dl></article>{user.role==='donor'&&<article className="panel"><h2>Offer help</h2><p>Your contact details are not displayed publicly. Coordination begins only after the offer is accepted.</p>{success?<div className="message">{success}</div>:<DonationForm need={need} onSubmit={submit} saving={saving}/>}</article>}</div>}</PageLayout>}
