"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Need={id:string;title:string;organization_name:string;location:string;priority:string;quantity_required:number;quantity_fulfilled:number;deadline:number;category:string;description?:string};
type Donation={id:string;title:string;quantity:number;condition:string;location:string;status:string;category:string};
type Activity={id:string;title:string;message:string;created_at:number;type:string};
type Match=Need&{score:number;reasons:string[]};
type Data={user:{displayName:string}|null;profile:{role:string}|null;needs:Need[];donations:Donation[];offers:unknown[];activity:Activity[]};
const fallback:Need[]=[{id:"need-bags",title:"School bags for the new term",organization_name:"Sahana Children’s Trust",location:"Kalutara",priority:"Urgent",quantity_required:20,quantity_fulfilled:12,deadline:Date.now()+345600000,category:"Education",description:"Durable school bags for students beginning a new academic term."},{id:"need-laptops",title:"Laptops for a learning lab",organization_name:"Mannar Youth Foundation",location:"Mannar",priority:"High",quantity_required:8,quantity_fulfilled:3,deadline:Date.now()+777600000,category:"Technology",description:"Working laptops for supervised digital learning sessions."},{id:"need-desks",title:"Study desks for a community centre",organization_name:"Bright Futures Lanka",location:"Gampaha",priority:"Medium",quantity_required:15,quantity_fulfilled:6,deadline:Date.now()+1036800000,category:"Furniture",description:"Study desks for an after-school learning programme."}];
const icons:Record<string,string>={Education:"🎒",Technology:"💻",Furniture:"🪑",Clothing:"👕",Books:"📚",Other:"📦"};
const navIcons:Record<string,string>={Overview:"⌂","Verified needs":"◇","My donations":"□",Matches:"↗",Messages:"○","Impact report":"◎",Organizations:"♙",Settings:"⚙"};

export default function Home(){
 const [tab,setTab]=useState("Overview"),[query,setQuery]=useState(""),[filter,setFilter]=useState("All needs"),[data,setData]=useState<Data|null>(null),[modal,setModal]=useState(false),[authOpen,setAuthOpen]=useState<"login"|"register"|null>(null),[selectedNeed,setSelectedNeed]=useState<Need|null>(null),[saving,setSaving]=useState(false),[matches,setMatches]=useState<Match[]>([]),[donationId,setDonationId]=useState(""),[notice,setNotice]=useState("");
 const load=()=>fetch("/api/dashboard").then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>{});useEffect(load,[]);
 const needs=data?.needs??fallback,donations=data?.donations??[],activity=data?.activity??[],signedIn=Boolean(data?.user);
 const filtered=useMemo(()=>needs.filter(n=>`${n.title} ${n.organization_name} ${n.location}`.toLowerCase().includes(query.toLowerCase())&&(filter==="All needs"||(filter==="Urgent"&&n.priority==="Urgent")||(filter==="Education"&&n.category==="Education")||filter==="Within 10 km")),[needs,query,filter]);
 const protect=(fn:()=>void)=>signedIn?fn():setAuthOpen("login");
 function navigate(item:string){if(["My donations","Matches","Messages","Settings"].includes(item)&&!signedIn){setAuthOpen("login");return}setTab(item)}
 async function register(role:string){setSaving(true);const r=await fetch("/api/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role})});setSaving(false);if(r.status===401){window.location.href="/signin-with-chatgpt?return_to=%2Fdashboard";return}if(r.ok){setAuthOpen(null);setNotice("Your Helping Hands profile is ready.");load();}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"createDonation",...body})});const result=await r.json();setSaving(false);if(r.status===401){setModal(false);setAuthOpen("login");return}if(r.ok){setDonationId(result.donationId);setMatches(result.matches);setModal(false);setTab("Matches");setNotice("Donation published. Your explainable matches are ready.");load();}}
 async function offer(m:Match){const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"offer",donationId,needId:m.id,score:m.score,reasons:m.reasons})});if(r.ok){setMatches([]);setNotice("Offer submitted to the verified organization for review.");load();}}
 const utilityCopy:Record<string,string>={Messages:"Offer updates, notifications and delivery coordination messages will appear here.","Impact report":"Track fulfilled needs, items delivered and communities reached through transparent impact reporting.",Organizations:"Discover trusted NGOs, schools and community organizations participating in the network.",Settings:"Manage your account, privacy, role and notification preferences."};
 const role=data?.profile?.role??"guest";
 const roleAction=role==="requester"?{label:"Create need request",copy:"Submit a request for community verification",icon:"◇"}:role==="verifier"?{label:"Review verification queue",copy:"Assess evidence and record a human decision",icon:"✓"}:role==="admin"?{label:"Open admin overview",copy:"Manage users, reports, risk flags and categories",icon:"⚙"}:{label:"Post a donation",copy:"List a useful item and receive smart matches",icon:"♡"};
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark">H</span><div><strong>Helping Hands</strong><small>Verified Giving Network</small></div></div><nav aria-label="Main navigation">{["Overview","Verified needs","My donations","Matches","Messages"].map(item=><button key={item} className={tab===item?"nav-item active":"nav-item"} onClick={()=>navigate(item)}><span>{navIcons[item]}</span>{item}{item==="Messages"&&signedIn&&<em>3</em>}</button>)}</nav><div className="nav-label">DISCOVER</div><nav>{["Impact report","Organizations","Settings"].map(item=><button key={item} className={tab===item?"nav-item active":"nav-item"} onClick={()=>navigate(item)}><span>{navIcons[item]}</span>{item}</button>)}</nav><div className="support-card"><span>♧</span><strong>Need support?</strong><p>Our partnership team is here to help.</p><button onClick={()=>setNotice("Support centre opened. Choose a topic to get guidance.")}>Contact support</button></div>{data?.user?<div className="profile"><div className="avatar">{data.user.displayName.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><strong>{data.user.displayName}</strong><small>{data.profile?.role??"Member"}</small></div><a href="/signout-with-chatgpt?return_to=%2F" aria-label="Sign out">↪</a></div>:<div className="profile guest-profile"><div className="avatar">?</div><div><strong>Guest visitor</strong><small>Public access</small></div><button onClick={()=>setAuthOpen("login")}>Login</button></div>}</aside>
  <section className="content"><header className="topbar"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search needs, organizations or locations" /></label><div className="top-actions">{signedIn?<><button aria-label="Notifications" className="icon-button" onClick={()=>navigate("Messages")}>♢<i/></button><button className="create" onClick={()=>setModal(true)}>＋ Create donation</button></>:<><button className="login-button" onClick={()=>setAuthOpen("login")}>Login</button><button className="create" onClick={()=>setAuthOpen("register")}>Register</button></>}</div></header><div className="page">
   {notice&&<div className="toast" role="status">✓ {notice}<button onClick={()=>setNotice("")}>×</button></div>}
   <div className="welcome"><div><p className="eyebrow">TRUSTED COMMUNITY GIVING</p><h1>{tab==="Overview"?(data?.user?`Welcome back, ${data.user.displayName.split(" ")[0]}.`:"Give what you do not need. Help someone who does."):tab}</h1><p>{tab==="Overview"?(signedIn?"Here is how your giving is making a difference.":"Explore genuine needs reviewed by trusted community organizations."):"Clear information, accountable actions and protected personal data."}</p></div><div className="verified"><span>✓</span><div><strong>{signedIn?"Secure member account":"Verified needs only"}</strong><small>{signedIn?"Protected identity · role-based access":"Human-reviewed organizations and requests"}</small></div></div></div>
   <section className="metrics"><article><span className="metric-icon mint">↗</span><div><small>My active donations</small><strong>{donations.filter(d=>d.status!=="completed").length}</strong><p>{signedIn?"Saved to your account":"Login to start giving"}</p></div></article><article><span className="metric-icon peach">♡</span><div><small>Verified needs</small><strong>{needs.length}</strong><p>From trusted organizations</p></div></article><article><span className="metric-icon lilac">⌁</span><div><small>Items still needed</small><strong>{needs.reduce((a,n)=>a+n.quantity_required-n.quantity_fulfilled,0)}</strong><p>Open for contribution</p></div></article><article><span className="metric-icon gold">✓</span><div><small>Pending offers</small><strong>{data?.offers.length??0}</strong><p>Awaiting human review</p></div></article></section>
   <section className="workflow-panel panel"><div><p className="eyebrow">WORKING FLOW</p><h2>Verified needs first. Smart donor matching.</h2><p>Requests remain private until a trusted human verifier approves them.</p></div><ol>{["Request","Review","Verified","Match","Offer","Accept","Handover","Complete"].map((step,index)=><li key={step}><span>{index+1}</span>{step}</li>)}</ol><button onClick={()=>role==="donor"?protect(()=>setModal(true)):setNotice(`${roleAction.label} opened for your ${role} workspace.`)}><b>{roleAction.icon}</b><span><strong>{roleAction.label}</strong><small>{roleAction.copy}</small></span>→</button></section>
   {utilityCopy[tab]?<section className="panel records info-page"><p className="eyebrow">HELPING HANDS</p><h2>{tab}</h2><p>{utilityCopy[tab]}</p><button className="create" onClick={()=>setNotice(`${tab} is connected to your Helping Hands workspace.`)}>Explore {tab.toLowerCase()}</button></section>:tab==="My donations"?<section className="panel records"><div className="panel-head"><div><h2>My donations</h2><p>Listings and current workflow status.</p></div><button onClick={()=>setModal(true)}>＋ Add donation</button></div>{donations.length?donations.map(d=><button className="record record-button" key={d.id} onClick={()=>setNotice(`${d.title}: ${d.status}`)}><span>{icons[d.category]??"📦"}</span><div><h3>{d.title}</h3><p>{d.quantity} items · {d.condition} · {d.location}</p></div><b className={`status ${d.status}`}>{d.status}</b></button>):<div className="empty">No donations yet. Create your first listing to receive verified matches.</div>}</section>:
   <section className="main-grid"><div className="panel needs-panel"><div className="panel-head"><div><h2>Verified needs</h2><p>Live requests reviewed by trusted organizations.</p></div><button onClick={()=>setTab("Verified needs")}>View all →</button></div><div className="filter-row">{["All needs","Urgent","Education","Within 10 km"].map(x=><button key={x} className={filter===x?"chip selected":"chip"} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="need-list">{filtered.map(n=>{const pct=Math.round(n.quantity_fulfilled/n.quantity_required*100),days=Math.max(0,Math.ceil((n.deadline-Date.now())/86400000));return <article className="need" key={n.id}><div className="need-image">{icons[n.category]??"📦"}<span className={`priority ${n.priority.toLowerCase()}`}>{n.priority}</span></div><div className="need-body"><div className="need-title"><h3>{n.title}</h3><span>✓ Verified</span></div><p className="org">{n.organization_name}</p><p className="meta">⌖ {n.location} · {n.category}</p><div className="progress-label"><span>{n.quantity_fulfilled} of {n.quantity_required} items fulfilled</span><b>{pct}%</b></div><div className="bar"><i style={{width:`${pct}%`}}/></div></div><div className="need-action"><small>{days} days left</small><button onClick={()=>setSelectedNeed(n)}>View need</button><button onClick={()=>protect(()=>setModal(true))}>I can help</button></div></article>})}{!filtered.length&&<div className="empty">No verified needs match your search.</div>}</div></div>
    <aside className="right-column"><div className="panel match-card"><div className="spark">✦</div><p className="eyebrow">SMART MATCH</p><h2>{matches.length?`${matches.length} matches ready`:"Turn useful items into verified impact"}</h2>{matches.length?<>{matches.slice(0,2).map(m=><div className="match-preview" key={m.id}><span>{icons[m.category]??"📦"}</span><div><strong>{m.title}</strong><small>{m.reasons.slice(0,2).join(" · ")}</small></div><b>{m.score}%</b><button className="offer-button" onClick={()=>offer(m)}>Offer</button></div>)}</>:<p>Create a donation and our transparent engine will compare category, quantity, location and urgency.</p>}<button onClick={()=>matches.length?setTab("Matches"):protect(()=>setModal(true))}>{matches.length?"Review all matches":"Create a donation"} <span>→</span></button><small className="explain">ⓘ Technology supports matching; verified organizations make final decisions.</small></div><div className="panel activity"><div className="panel-head"><div><h2>Recent activity</h2></div><button onClick={()=>navigate("Messages")}>View all</button></div><ul>{activity.length?activity.map(a=><li key={a.id}><span className="activity-icon success">✓</span><div><strong>{a.title}</strong><p>{a.message}</p><small>{new Date(a.created_at).toLocaleDateString()}</small></div></li>):<li><span className="activity-icon info">◇</span><div><strong>{signedIn?"Account ready":"Public browsing enabled"}</strong><p>{signedIn?"Your secure activity history will appear here.":"Login to save donations and track your impact."}</p><small>Now</small></div></li>}</ul></div></aside></section>}
   <footer><button onClick={()=>setTab("Impact report")}>Impact</button><button onClick={()=>setTab("Organizations")}>Organizations</button><button onClick={()=>setNotice("Privacy and safety standards opened.")}>Privacy & safety</button><button onClick={()=>setNotice("Verification standards opened.")}>Verification standards</button><button onClick={()=>setNotice("Help centre opened.")}>Help centre</button></footer></div></section>
  {authOpen&&<div className="modal-backdrop"><section className="donation-modal auth-modal"><button className="close" onClick={()=>setAuthOpen(null)}>×</button><p className="eyebrow">SECURE ACCESS</p><h2>{authOpen==="login"?"Welcome back":"Join Helping Hands"}</h2><p>{authOpen==="login"?"Login securely to manage your requests, donations, reviews and impact history.":"Choose your primary role. Administrators and verifiers require platform approval."}</p>{authOpen==="register"&&<div className="role-grid four-roles">{[["donor","♡","Donor","Give useful items"],["requester","◇","Requester","Request verified help"],["verifier","✓","Verifier","Review community needs"],["admin","⚙","Admin","Manage the platform"]].map(([role,icon,title,copy])=><button key={role} onClick={()=>register(role)} disabled={saving}><span>{icon}</span><strong>{title}</strong><small>{copy}</small></button>)}</div>}<a className="auth-primary" href="/signin-with-chatgpt?return_to=%2Fdashboard">Continue securely with ChatGPT</a><p className="auth-switch">{authOpen==="login"?"New to Helping Hands? ":"Already registered? "}<button onClick={()=>setAuthOpen(authOpen==="login"?"register":"login")}>{authOpen==="login"?"Create an account":"Login"}</button></p><small className="auth-privacy">We never publish your private contact details or residential address.</small></section></div>}
  {selectedNeed&&<div className="modal-backdrop"><section className="donation-modal need-detail"><button className="close" onClick={()=>setSelectedNeed(null)}>×</button><div className="detail-icon">{icons[selectedNeed.category]??"📦"}</div><p className="eyebrow">VERIFIED COMMUNITY NEED</p><h2>{selectedNeed.title}</h2><div className="verified-line">✓ Verified by {selectedNeed.organization_name}</div><p>{selectedNeed.description??"This request has been reviewed by an approved community organization."}</p><dl><div><dt>Location</dt><dd>{selectedNeed.location}</dd></div><div><dt>Priority</dt><dd>{selectedNeed.priority}</dd></div><div><dt>Progress</dt><dd>{selectedNeed.quantity_fulfilled} of {selectedNeed.quantity_required} fulfilled</dd></div></dl><button className="submit" onClick={()=>{setSelectedNeed(null);protect(()=>setModal(true))}}>I can help with this need</button></section></div>}
  {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="donation-modal" onSubmit={create}><button type="button" className="close" onClick={()=>setModal(false)}>×</button><p className="eyebrow">DONOR WORKFLOW</p><h2>Create a donation</h2><p>Describe what you can give. We will find suitable verified needs.</p><label>Item title<input name="title" required placeholder="e.g. Children’s story books"/></label><div className="form-grid"><label>Category<select name="category"><option>Education</option><option>Technology</option><option>Furniture</option><option>Clothing</option><option>Books</option><option>Other</option></select></label><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Condition<select name="condition"><option>New</option><option>Like new</option><option>Good</option><option>Fair</option></select></label><label>Location<select name="location"><option>Kalutara</option><option>Gampaha</option><option>Colombo</option><option>Mannar</option><option>Kandy</option></select></label></div><label>Description<textarea name="description" placeholder="Add details about the items and pickup availability"/></label><div className="safety-note">✓ Your exact address remains private until an offer is accepted.</div><button className="submit" disabled={saving}>{saving?"Publishing…":"Publish and find matches"}</button></form></div>}
 </main>;
}
