"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
type Need={id:string;title:string;organization_name:string;location:string;priority:string;quantity_required:number;quantity_fulfilled:number;deadline:number;category:string};
type Donation={id:string;title:string;quantity:number;condition:string;location:string;status:string;category:string};
type Activity={id:string;title:string;message:string;created_at:number;type:string};
type Match=Need&{score:number;reasons:string[]};
type Data={user:{displayName:string};needs:Need[];donations:Donation[];offers:unknown[];activity:Activity[]};
const fallback:Need[]=[{id:"need-bags",title:"School bags for new term",organization_name:"Sahana Children’s Trust",location:"Kalutara",priority:"Urgent",quantity_required:20,quantity_fulfilled:12,deadline:Date.now()+345600000,category:"Education"},{id:"need-laptops",title:"Laptops for learning lab",organization_name:"Mannar Youth Foundation",location:"Mannar",priority:"High",quantity_required:8,quantity_fulfilled:3,deadline:Date.now()+777600000,category:"Technology"},{id:"need-desks",title:"Study desks for community centre",organization_name:"Bright Futures Lanka",location:"Gampaha",priority:"Medium",quantity_required:15,quantity_fulfilled:6,deadline:Date.now()+1036800000,category:"Furniture"}];
const icons:Record<string,string>={Education:"🎒",Technology:"💻",Furniture:"🪑",Clothing:"👕",Books:"📚",Other:"📦"};
export default function Home(){
 const [tab,setTab]=useState("Overview"),[query,setQuery]=useState(""),[data,setData]=useState<Data|null>(null),[modal,setModal]=useState(false),[saving,setSaving]=useState(false),[matches,setMatches]=useState<Match[]>([]),[donationId,setDonationId]=useState(""),[notice,setNotice]=useState("");
 const load=()=>fetch("/api/dashboard").then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>{});useEffect(load,[]);
 const needs=data?.needs??fallback,donations=data?.donations??[],activity=data?.activity??[];
 const filtered=useMemo(()=>needs.filter(n=>`${n.title} ${n.organization_name} ${n.location}`.toLowerCase().includes(query.toLowerCase())),[needs,query]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget),body=Object.fromEntries(f.entries());const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"createDonation",...body})});const result=await r.json();setSaving(false);if(r.ok){setDonationId(result.donationId);setMatches(result.matches);setModal(false);setNotice("Donation published — explainable matches are ready.");load();}}
 async function offer(m:Match){const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"offer",donationId,needId:m.id,score:m.score,reasons:m.reasons})});if(r.ok){setMatches([]);setNotice("Offer submitted to the verified organization for review.");load();}}
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark">H</span><div><strong>Helping Hands</strong><small>உதவிக்கரங்கள்</small></div></div><nav aria-label="Main navigation">{["Overview","Verified needs","My donations","Matches","Messages"].map(item=><button key={item} className={tab===item?"nav-item active":"nav-item"} onClick={()=>setTab(item)}><span>{({Overview:"⌂","Verified needs":"◇","My donations":"□",Matches:"↗",Messages:"○"} as Record<string,string>)[item]}</span>{item}{item==="Messages"&&<em>3</em>}</button>)}</nav><div className="nav-label">ORGANIZATION</div><nav><button className="nav-item"><span>◎</span>Impact report</button><button className="nav-item"><span>♙</span>Team & access</button><button className="nav-item"><span>⚙</span>Settings</button></nav><div className="support-card"><span>♧</span><strong>Need support?</strong><p>Our partnership team is here to help.</p><button>Contact support</button></div><div className="profile"><div className="avatar">{(data?.user.displayName??"Anjali Mendis").split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><strong>{data?.user.displayName??"Anjali Mendis"}</strong><small>Verified member</small></div><button aria-label="Profile menu">⋮</button></div></aside>
  <section className="content"><header className="topbar"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search needs, organizations, locations…" /></label><div className="top-actions"><button aria-label="Notifications" className="icon-button">♢<i/></button><button className="create" onClick={()=>setModal(true)}>＋ Create donation</button></div></header><div className="page">
   {notice&&<div className="toast" role="status">✓ {notice}<button onClick={()=>setNotice("")}>×</button></div>}
   <div className="welcome"><div><p className="eyebrow">LIVE OPERATIONS DASHBOARD</p><h1>{tab==="Overview"?`Good morning, ${(data?.user.displayName??"Anjali").split(" ")[0]}.`:tab}</h1><p>{tab==="Overview"?"Here’s how your giving is making a difference.":"Your secure, verified Helping Hands records."}</p></div><div className="verified"><span>✓</span><div><strong>Verified platform member</strong><small>Secure identity · role-based access</small></div></div></div>
   <section className="metrics"><article><span className="metric-icon mint">↗</span><div><small>My active donations</small><strong>{donations.filter(d=>d.status!=="completed").length}</strong><p>Durably saved</p></div></article><article><span className="metric-icon peach">♡</span><div><small>Verified needs</small><strong>{needs.length}</strong><p>Across trusted organizations</p></div></article><article><span className="metric-icon lilac">⌁</span><div><small>Items still needed</small><strong>{needs.reduce((a,n)=>a+n.quantity_required-n.quantity_fulfilled,0)}</strong><p>Open for contribution</p></div></article><article><span className="metric-icon gold">✓</span><div><small>Pending offers</small><strong>{data?.offers.length??0}</strong><p>Awaiting human review</p></div></article></section>
   {tab==="My donations"?<section className="panel records"><div className="panel-head"><div><h2>My donations</h2><p>Listings and their current workflow status.</p></div><button onClick={()=>setModal(true)}>＋ Add donation</button></div>{donations.length?donations.map(d=><article className="record" key={d.id}><span>{icons[d.category]??"📦"}</span><div><h3>{d.title}</h3><p>{d.quantity} items · {d.condition} · {d.location}</p></div><b className={`status ${d.status}`}>{d.status}</b></article>):<div className="empty">No donations yet. Create your first listing to receive verified matches.</div>}</section>:
   <section className="main-grid"><div className="panel needs-panel"><div className="panel-head"><div><h2>Verified needs near you</h2><p>Live requests reviewed by trusted organizations.</p></div><button onClick={()=>setTab("Verified needs")}>View all →</button></div><div className="filter-row"><button className="chip selected">All needs</button><button className="chip">Urgent</button><button className="chip">Education</button><button className="chip">Within 10 km</button></div><div className="need-list">{filtered.map(n=>{const pct=Math.round(n.quantity_fulfilled/n.quantity_required*100),days=Math.max(0,Math.ceil((n.deadline-Date.now())/86400000));return <article className="need" key={n.id}><div className="need-image">{icons[n.category]??"📦"}<span className={`priority ${n.priority.toLowerCase()}`}>{n.priority}</span></div><div className="need-body"><div className="need-title"><h3>{n.title}</h3><span>✓ Verified</span></div><p className="org">{n.organization_name}</p><p className="meta">⌖ {n.location} · {n.category}</p><div className="progress-label"><span>{n.quantity_fulfilled} of {n.quantity_required} items fulfilled</span><b>{pct}%</b></div><div className="bar"><i style={{width:`${pct}%`}}/></div></div><div className="need-action"><small>{days} days left</small><button onClick={()=>setModal(true)}>I can help</button></div></article>})}{!filtered.length&&<div className="empty">No verified needs match your search.</div>}</div></div>
    <aside className="right-column"><div className="panel match-card"><div className="spark">✦</div><p className="eyebrow">SMART MATCH</p><h2>{matches.length?`${matches.length} matches ready`:"Turn useful items into verified impact"}</h2>{matches.length?<>{matches.slice(0,2).map(m=><div className="match-preview" key={m.id}><span>{icons[m.category]??"📦"}</span><div><strong>{m.title}</strong><small>{m.reasons.slice(0,2).join(" · ")}</small></div><b>{m.score}%</b><button className="offer-button" onClick={()=>offer(m)}>Offer</button></div>)}</>:<p>Create a donation and our transparent scoring engine will compare category, quantity, location and urgency.</p>}<button onClick={()=>matches.length?setTab("Matches"):setModal(true)}>{matches.length?"Review all matches":"Create a donation"} <span>→</span></button><small className="explain">ⓘ AI supports matching; verified organizations make final decisions.</small></div>
    <div className="panel activity"><div className="panel-head"><div><h2>Recent activity</h2></div><button>View all</button></div><ul>{activity.length?activity.map(a=><li key={a.id}><span className="activity-icon success">✓</span><div><strong>{a.title}</strong><p>{a.message}</p><small>{new Date(a.created_at).toLocaleDateString()}</small></div></li>):<li><span className="activity-icon info">◇</span><div><strong>Workspace ready</strong><p>Your secure activity history will appear here.</p><small>Now</small></div></li>}</ul></div></aside></section>}
   <footer><span>Helping Hands · Built for accountable giving</span><span>Privacy & safety · Verification standards · Help centre</span></footer></div></section>
  {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="donation-modal" onSubmit={create}><button type="button" className="close" onClick={()=>setModal(false)} aria-label="Close">×</button><p className="eyebrow">DONOR WORKFLOW</p><h2>Create a donation</h2><p>Describe what you can give. We’ll find suitable verified needs.</p><label>Item title<input name="title" required placeholder="e.g. Children’s story books"/></label><div className="form-grid"><label>Category<select name="category"><option>Education</option><option>Technology</option><option>Furniture</option><option>Clothing</option><option>Books</option><option>Other</option></select></label><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Condition<select name="condition"><option>New</option><option>Like new</option><option>Good</option><option>Fair</option></select></label><label>Location<select name="location"><option>Kalutara</option><option>Gampaha</option><option>Colombo</option><option>Mannar</option><option>Kandy</option></select></label></div><label>Description<textarea name="description" placeholder="Add useful details about the items and pickup availability"/></label><div className="safety-note">✓ Your exact address remains private until an offer is accepted.</div><button className="submit" disabled={saving}>{saving?"Publishing…":"Publish and find matches"}</button></form></div>}
 </main>}
