import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";

const schema = [
  "CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'donor', created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, location TEXT NOT NULL, verification_status TEXT NOT NULL DEFAULT 'pending', verified_at INTEGER)",
  "CREATE TABLE IF NOT EXISTS needs (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, item_type TEXT NOT NULL, quantity_required INTEGER NOT NULL, quantity_fulfilled INTEGER NOT NULL DEFAULT 0, location TEXT NOT NULL, priority TEXT NOT NULL, deadline INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS donations (id TEXT PRIMARY KEY, donor_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, item_type TEXT NOT NULL, quantity INTEGER NOT NULL, condition TEXT NOT NULL, location TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'available', created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS offers (id TEXT PRIMARY KEY, donation_id TEXT NOT NULL, need_id TEXT NOT NULL, donor_id TEXT NOT NULL, offered_quantity INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', matching_score INTEGER NOT NULL, matching_reasons TEXT NOT NULL, created_at INTEGER NOT NULL)",
  "CREATE TABLE IF NOT EXISTS activities (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, created_at INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_needs_status_priority ON needs(status, priority)",
  "CREATE INDEX IF NOT EXISTS idx_donations_donor_status ON donations(donor_id, status)",
  "CREATE INDEX IF NOT EXISTS idx_offers_donor_status ON offers(donor_id, status)",
];
async function setup(){const db=env.DB;await db.batch(schema.map(sql=>db.prepare(sql)));const count=await db.prepare("SELECT COUNT(*) AS count FROM needs").first<{count:number}>();if((count?.count??0)>0)return;const now=Date.now(),day=86400000;await db.batch([
  db.prepare("INSERT INTO organizations VALUES (?, ?, ?, 'verified', ?)").bind("org-sahana","Sahana Children’s Trust","Kalutara",now-160*day),db.prepare("INSERT INTO organizations VALUES (?, ?, ?, 'verified', ?)").bind("org-mannar","Mannar Youth Foundation","Mannar",now-120*day),db.prepare("INSERT INTO organizations VALUES (?, ?, ?, 'verified', ?)").bind("org-bright","Bright Futures Lanka","Gampaha",now-90*day),
  db.prepare("INSERT INTO needs VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?)").bind("need-bags","org-sahana","School bags for new term","School bags for students starting the new term.","Education","School bags",20,12,"Kalutara","Urgent",now+4*day,now-5*day),db.prepare("INSERT INTO needs VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?)").bind("need-laptops","org-mannar","Laptops for learning lab","Working laptops for a community learning lab.","Technology","Laptops",8,3,"Mannar","High",now+9*day,now-8*day),db.prepare("INSERT INTO needs VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?)").bind("need-desks","org-bright","Study desks for community centre","Desks for supervised after-school study sessions.","Furniture","Study desks",15,6,"Gampaha","Medium",now+12*day,now-3*day)]);}
async function currentUser(){const auth=await getChatGPTUser();const user=auth??{userId:"demo-anjali",email:"anjali@helpinghands.lk",displayName:"Anjali Mendis",fullName:"Anjali Mendis"};await env.DB.prepare("INSERT OR IGNORE INTO users VALUES (?, ?, ?, 'donor', ?)").bind(user.userId,user.email,user.displayName,Date.now()).run();return user;}
export async function GET(){await setup();const user=await currentUser();const needs=await env.DB.prepare("SELECT n.*, o.name AS organization_name, o.verification_status FROM needs n JOIN organizations o ON o.id=n.organization_id WHERE n.status='active' ORDER BY CASE n.priority WHEN 'Urgent' THEN 1 WHEN 'High' THEN 2 ELSE 3 END, n.deadline").all();const donations=await env.DB.prepare("SELECT * FROM donations WHERE donor_id=? ORDER BY created_at DESC").bind(user.userId).all();const offers=await env.DB.prepare("SELECT f.*, n.title AS need_title FROM offers f JOIN needs n ON n.id=f.need_id WHERE f.donor_id=? ORDER BY f.created_at DESC").bind(user.userId).all();const activity=await env.DB.prepare("SELECT * FROM activities WHERE user_id=? ORDER BY created_at DESC LIMIT 6").bind(user.userId).all();return Response.json({user,needs:needs.results,donations:donations.results,offers:offers.results,activity:activity.results});}
export async function POST(request:Request){await setup();const user=await currentUser();const body=await request.json() as Record<string,unknown>;if(body.action==="createDonation"){const quantity=Math.max(1,Number(body.quantity)||1),id=crypto.randomUUID(),now=Date.now();await env.DB.batch([env.DB.prepare("INSERT INTO donations VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'available', ?)").bind(id,user.userId,String(body.title),String(body.description||body.title),String(body.category),String(body.itemType||body.title),quantity,String(body.condition||"Good"),String(body.location),now),env.DB.prepare("INSERT INTO activities VALUES (?, ?, 'donation', 'Donation published', ?, ?)").bind(crypto.randomUUID(),user.userId,`${quantity} × ${String(body.title)} is now available for verified needs.`,now)]);const candidates=await env.DB.prepare("SELECT n.*, o.name AS organization_name FROM needs n JOIN organizations o ON o.id=n.organization_id WHERE n.status='active'").all<Record<string,unknown>>();const matches=candidates.results.map(n=>{const cat=String(n.category).toLowerCase()===String(body.category).toLowerCase()?45:10,loc=String(n.location).toLowerCase()===String(body.location).toLowerCase()?25:8,urg=n.priority==='Urgent'?20:n.priority==='High'?14:8,qty=Math.min(10,Math.round(quantity/Math.max(1,Number(n.quantity_required)-Number(n.quantity_fulfilled))*10));return{...n,score:Math.min(98,cat+loc+urg+qty),reasons:[cat===45?"category match":"related category",loc===25?"same location":"location considered",`${String(n.priority).toLowerCase()} priority`,"quantity compatibility"]};}).sort((a,b)=>b.score-a.score).slice(0,4);return Response.json({ok:true,donationId:id,matches});}if(body.action==="offer"){const need=await env.DB.prepare("SELECT * FROM needs WHERE id=? AND status='active'").bind(String(body.needId)).first<Record<string,unknown>>(),donation=await env.DB.prepare("SELECT * FROM donations WHERE id=? AND donor_id=?").bind(String(body.donationId),user.userId).first<Record<string,unknown>>();if(!need||!donation)return Response.json({error:"Record not found"},{status:404});const offered=Math.min(Number(donation.quantity),Number(need.quantity_required)-Number(need.quantity_fulfilled)),score=Number(body.score)||75,now=Date.now();await env.DB.batch([env.DB.prepare("INSERT INTO offers VALUES (?, ?, ?, ?, ?, 'pending', ?, ?, ?)").bind(crypto.randomUUID(),String(body.donationId),String(body.needId),user.userId,offered,score,JSON.stringify(body.reasons||[]),now),env.DB.prepare("UPDATE donations SET status='offered' WHERE id=?").bind(String(body.donationId)),env.DB.prepare("INSERT INTO activities VALUES (?, ?, 'offer', 'Offer submitted', ?, ?)").bind(crypto.randomUUID(),user.userId,`Your offer for ${String(need.title)} is awaiting organization review.`,now)]);return Response.json({ok:true});}return Response.json({error:"Unsupported action"},{status:400});}
